version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskflow-rabbitmq
    ports:
      - "5672:5672"       # RabbitMQ için AMQP portu
      - "15672:15672"     # Yönetim paneli (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: taskflow-redis
    ports:
      - "6379:6379"
